### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by oneStarCai** [flaribbit/love2d-lua-websocket#8]
![image](https://github.com/flaribbit/love2d-lua-websocket/assets/4077572/2444feeb-9110-4ba4-b866-b2b1326bc5f2)
 

```
elseif self.status==STATUS.CONNECTING then
     local res = sock:receive("*l")
```

```
when I call :
 local client = require("websocket").new("127.0.0.1", 9951) 
while true do
    love.update()
end  
``` 
receive nothing, res is nil. how to resolve it?

**Comment by oneStarCai** [comment]
![image](https://github.com/flaribbit/love2d-lua-websocket/assets/4077572/8e0cec6e-aa70-4f40-b09e-4cc2e0e69eb1)

**Comment by flaribbit** [comment]
That's weird. Thanks for your feedback. But I'm on vacation now. I'll check it 2 days later.

BTW, which language/library is your websocket server written in?

**Comment by oneStarCai** [comment]
您的邮件已收到，我会尽快查看并回复。。。
